### ISSUE TITLE
udevadm not found when running make

### ISSUE THREAD

**Issue by theshinyknight** [tangentsoft/pidp8i#1]
I am getting an error when running make.

Everything run fine, during the install phase, it start installing system files on the pi device, and goes as far as "Setting real-time priority capabilities on pudp8i-sim" and Setting real-time priority capabilities on pudp8i-test"; but the next line says

"/bin/sh: 7: /sbin/udevadm: not found"

and goes back to prompt.

When I reboot the Pi I can see the panel light up and seems to be booting the OS automatically; some lights are flickering (no switch are set, so it is loading the default config). I can run pidp8i and it load OS-8 with the RK05 cartridge, so it seems that it is working fine, but I am not sure what is actually not done after that line that fail.

Using a Raspberry PI Zero 2W with a 8 GB SD card with the latest console version of Raspbian OS; and the PDP8i kit

**Comment by tangentsoft** [comment]
It's due to a change in the OS platforms since the version of Raspbian we originally shipped. There's [a fix on trunk](https://tangentsoft.com/pidp8i/timeline?y=ci&c=41daa2863ba05495cd94) to solve this. [Update to the latest](https://tangentsoft.com/pidp8i/#updating) to get the fix.
